### ISSUE TITLE
SoapHeaders

### ISSUE THREAD

**Issue by tjphippen** [meng-tian/async-soap-guzzle#12]
Prior to using this package I used __setSoapHeaders to set my authentication. Doesn't seem to be any way to do that now..?

**Comment by MRZMUH001** [comment]
You can try setting authentication in the client call interface. 

     * @param string $function_name     The name of the SOAP function to interpret.
     * @param array  $arguments         An array of the arguments to $function_name.
     * @param array  $options           An associative array of options.
     *                                  The location option is the URL of the remote Web service.
     *                                  The uri option is the target namespace of the SOAP service.
     *                                  The soapaction option is the action to call.
     * @param mixed  $input_headers     An array of headers to be interpreted along with the SOAP request.

$client->call($name, array $arguments, array $options = null, $inputHeaders = null, array &$outputHeaders = null)

**Comment by realmtian** [comment]
Hi @tjphippen , @MRZMUH001 is right. You should be able to send SOAP headers using either `call` or `callAsync`. Could you please try it?

**Comment by realmtian** [comment]
@tjphippen , any progress sharing with us?

**Comment by realmtian** [comment]
Closing the issue as it is no longer active. Will reopen it if the reporter responds.
