### ISSUE TITLE
How to implement custom header ?

### ISSUE THREAD

**Issue by yamenarahman** [meng-tian/async-soap-guzzle#13]
![soap](https://user-images.githubusercontent.com/24607365/27993242-67c4cf92-64a6-11e7-996b-4801cbf1c6bd.JPG)

How can I implement a custom header like this ?
Any help appreciated, Thanks!

**Comment by realmtian** [comment]
Hi @zLegend-210 , the below code should help you start with setting custom SOAP input headers:
```php
require 'vendor/autoload.php';

$factory = new \Meng\AsyncSoap\Guzzle\Factory();
$client = $factory->create(new \GuzzleHttp\Client(), 'http://www.mysoapserver.com?WSDL');

$client->call(
    'MySoapFunction',
    ['arg1', 'arg2', 'arg3'],
    [
        new SoapHeader('www.mynamespace.com', 'username', 'admin'),
        new SoapHeader('www.mynamespace.com', 'password', 'changeme'),
    ]
);
```

Hope this helps.

**Comment by yamenarahman** [comment]
Thanks so much, I'm trying it now hope to solve this task.

**Comment by realmtian** [comment]
@zLegend-210 , does that code snippet work for you?

**Comment by realmtian** [comment]
Closing the issue due to no response. Will reopen the issue if the issue still not resolved.

**Comment by bunyamink** [comment]
Hi,

How can i add custom soap header to callAsync function?

Here what i tried:
`
         $factory = new Factory();

        $this->Client = $factory->create(new HttpClient([
            'timeout' => 15,
            'cache_wsdl' => WSDL_CACHE_BOTH,
            'trace' => true,
            'verify' => false,
            'stream_context' => stream_context_create(['http' => ['user_agent' => 'PHPSoapClient']]),
            'compression' => (SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP),
            'features' => SOAP_SINGLE_ELEMENT_ARRAYS
                ]), $this->config['wsdl']);
        
        $soapVarHeader = new SoapVar($headerPart, XSD_ANYXML);
        
        $header = new SoapHeader('http://ticketservice.atlasyazilim.com.tr', 'affiliateApprover', $soapVarHeader);

       $promise = $this->Client->callAsync($method, [$soapVar], [$header ])->then(function($response) 
           use($request, $method, $class, $callback, $result_method) {
            dd($this->Client->__getLastRequest());
            
        }, function($exception) use($method, $class) {
            dd($this->Client->__getLastRequest());
            
        });
`

and this did not work. Here the result of __getLastRequest():

`<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/">
    <SOAP-ENV:Body>
        <ns1:getJourneyList>
            <ns1:departure>ISTANBUL AVR</ns1:departure>
            <ns1:destination>ANKARA</ns1:destination>
            <ns1:journeyDate>2019-07-06</ns1:journeyDate>
        </ns1:getJourneyList>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**Comment by bunyamink** [comment]
I resolved the issued adding one more null variable to callAsync function:

Correct:

`$this->Client->callAsync($method, [$soapVar], null, [$header]);`

False:

`$this->Client->callAsync($method, [$soapVar], [$header]);`
