### ISSUE TITLE
How could the headers, options, and arguments be passed to the client?

### ISSUE THREAD

**Issue by crisvill** [meng-tian/async-soap-guzzle#15]
How could the headers, options & context options, and arguments be set to the client?
Can you provide a complete example that includes credentials, namespace, etc.?

**Comment by realmtian** [comment]
Hi @crisvill , what do you mean by `context options` here?

**Comment by crisvill** [comment]
I am referring to options such as:
Soap version, exceptions, trace, wsdl cache, stream context (ssl ...), soap namespace, Auth Header ....

I am new to soap, but I need to be able to connect to a service using username, password, your implementation seems good to me by the use of promises for asynchronous calls.
Perhaps you could add more advanced examples in the readme. Regards.

**Comment by realmtian** [comment]
https://github.com/meng-tian/async-soap-guzzle/blob/master/src/Factory.php#L22..L25 As can be found from the documentation, some options you mentioned are supported (e.g., soap version, exceptions, and target namespace are directly supported by `Factory` class; SSL and authentication can be configured by the guzzle client), but some are not (e.g., trace and wsdl cache). 

All supported options are either supported by PHP's `SoapClient` or Guzzle client. Examples should be easily found from corresponding documentations.

**Comment by realmtian** [comment]
If you need specific help for certain options you need, please provide me specific requirement so I can probably give you specific examples. Apologies I can't provide all examples you asked.

**Comment by MRZMUH001** [comment]
@crisvill - You could try do this:
```
 $options = [
            'soap_version' => 'SOAP_1_1',
            'stream_context' => stream_context_create(['http' => ['header' => HEADERS]]),
            'login' => AUTH_USER,
            'password' => AUTH_PASSWORD,
            'location' => API_URL,
            'trace' => DEBUG,
            'exceptions' => EXCEPTIONS
        ];
$factory = new Factory();
$client = $factory->create(new Client(), WSDL PATH, $options);
```

But note, some options are unset in the SoapInterpreter so might not work. You could try not unset them or directly pass these to the RequestBuilder where SoapHeaders are set (bypassing the unsets).

**Comment by realmtian** [comment]
Thanks @MRZMUH001 for trying to help. I would say passing all those options to the `$options` argument is not appropriate here. The underlying implementation of this package separates the responsibility of building the SOAP messages and transporting the SOAP messages. 

* If the `stream_context` is only used for specifying HTTP headers, the headers should be specified in the `$client` argument, i.e., the Guzzle client. 
* The same for the `login` and `password` option. Guzzle client is responsible for this.
* `trace` is not supported. 

I hope this helps.

**Comment by realmtian** [comment]
Closing the issue due to inactivity.
