### ISSUE TITLE
WSDL is not cached

### ISSUE THREAD

**Issue by berarma** [meng-tian/async-soap-guzzle#18]
Hi. Thanks for the library, it's working great here.

One minor annoyance is that SoapClient provides a ```wsdl_cache``` option that this library ignores, thus no WSDL is ever cached.

> The cache_wsdl option is one of WSDL_CACHE_NONE, WSDL_CACHE_DISK, WSDL_CACHE_MEMORY or WSDL_CACHE_BOTH.

The cache would improve performance.

**Comment by realmtian** [comment]
Hi @berarma , `wsdl_cache` is not supported by `Meng\AsyncSoap\Guzzle\Factory`. Generally, a program should only need to load the WSDL once for each web service, so the performance shouldn't be impacted too much. 

There is no plan to support `wsdl_cache ` in `Meng\AsyncSoap\Guzzle\Factory`. It shouldn't too difficult to add another level of indirection to accomplish the caching in your application code.

I hope this helps.

**Comment by realmtian** [comment]
Closing the issue. Please reopen if further assistance is needed.
