### ISSUE TITLE
SOAP-ERROR: Parsing Schema: can't import schema

### ISSUE THREAD

**Issue by ethmelly** [meng-tian/async-soap-guzzle#19]
Hello ,

I have a soap call where the namespace url is different from the wsdl url.

```
$client = new \SoapClient('http://example.com/?wsdl', []);
 
 $client->__setSoapHeaders(
            new \SoapHeader('http://other.domain.tld', 'AuthHeader', [
                'Username' => $this->user,
                'Password' => $this->password,
                'ResellerCode' => $this->code,
            ]));
$client->someFunction();
``` 
works

```
$factory = new \Meng\AsyncSoap\Guzzle\Factory();
$client = $factory->create(new \GuzzleHttp\Client(), 'http://example.com/?wsdl');

$client->call(
    'someFunction',
    [],
    [
        new SoapHeader('http://other.domain.tld',[
                'Username' => $this->user,
                'Password' => $this->password,
                'ResellerCode' => $this->code,
            ])
    ]
);
```

returns 
`SOAP-ERROR: Parsing Schema: can't import schema from 'data://text/xml/_types/CommonTypes.xsd'`

I'm guessing it's related to the namespace since i'm already using your package for other calls with no issues.

Is there anyway to set the namespace ?

**Comment by ethmelly** [comment]
Then wsdl looks like this

```
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:name="http://other.domain.tld" targetNamespace="http://other.domain.tld" name="ExampleWebServices">
<wsdl:types>
<xsd:schema targetNamespace="http://other.domain.tld">
<xsd:include schemaLocation="xml/_types/CommonTypes.xsd"/>
........
```
where i guess the include schemaLocation is the one generating the error for data://text/xml/_types/CommonTypes.xsd

**Comment by realmtian** [comment]
Hi @ethmelly , is it possible to share the real wsdl url? so I can test it.

**Comment by ethmelly** [comment]
Hi @meng-tian i think that their code is actually public so don't see why not :) [Repo](https://github.com/rredpoppy/aida)
```
wsdl http://aida.eximtur.ro/tourOperator/ws/?wsdl
namespace http://aida.dcsplus.net/ws/2010
```
Credentials i can't share but auth should be a different story

**Comment by realmtian** [comment]
@ethmelly Sorry for the late response. I believe that PHP's `SoapClient` will load the schema based on the `SchemaLocation` from WSDL, so it works fine.

However, the `\Meng\AsyncSoap\Guzzle\Factory` does not load schemas when load the WSDL. Loading schemas based on `SchemaLocation` is not supported by this library yet. 

I don't think the error is related to namespaces.

**Comment by ethmelly** [comment]
Hello @meng-tian , you think there's a workaround for this issue ? 
My project involves allot of async soap calls from multiple providers , as a temporary fix i made few calls with curl directly building the xml manually without Soap for this provider. 
Or maybe you can point me in the right direction and i will gladly make a PR request if i get a working solution. Your library helped and i will gladly help to maintain it if i can.

**Comment by realmtian** [comment]
@ethmelly , I would recommended to implement a class that is responsible for assembling schemas into the WSDL based on `SchemaLocation` (of course in a async manner). Then, you could pass the assembled WSDL as a data stream to `\Meng\AsyncSoap\Guzzle\Factory`. You can see how I use the data stream here: https://github.com/meng-tian/async-soap-guzzle/blob/master/src/Factory.php#L34

I haven't tried it yet. All PR are welcomed if it fits the style of this library and are tested thoroughly.

Good luck! 🎅

**Comment by realmtian** [comment]
Closing the issue due to inactivity.
