### ISSUE TITLE
SoapHeader

### ISSUE THREAD

**Issue by fyousof** [meng-tian/async-soap-guzzle#21]
Hi Meng, 

I am trying to achieve below header

`<soap:Header xmlns:wsa="http://www.w3.org/2005/08/addressing">
	<wsse:Security soap:mustUnderstand="true" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
		<wsse:UsernameToken wsu:Id="UsernameToken">
			<wsse:Username>USERNAME</wsse:Username>
			<wsse:Password Type="#PasswordText">PASS</wsse:Password>
			<wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">nEmCjKCvNwnnY5CfyOq3fQ==</wsse:Nonce>
			<wsu:Created>2018-01-11T13:09:16.157Z</wsu:Created>
		</wsse:UsernameToken>
	</wsse:Security>
	<wsa:Action>URL/Account_Get</wsa:Action>
	<wsa:To>URL/JavaAxis</wsa:To>
</soap:Header>`

Below are my codes 

```
$client = $this->factory->create(
            new \GuzzleHttp\Client(),
            'URL?WSDL',
            [
                'soap_version' => 'SOAP_1_2',
                'login'        => 'USERNAME',
                'password'     => 'PASSWORD',
                'location'     => 'URL/JavaAxis',
            ]
        );

$response = $client->call('FUNCTION_NAME', [['VAR_NAME' => 'VALUE']]);
```

So far it will only response NULL, anything that I've missed?

Appreciate your help.

**Comment by realmtian** [comment]
Hi @fyousof , the third parameter of `Meng\AsyncSoap\Guzzle\ SoapClient :: callAsync ` is input SOAP headers. You can pass an array of headers:

```
[new SoapHeader('www.namespace.com', 'test_header', 'header_data')]
```

**Comment by fyousof** [comment]
Thanks @meng-tian - I give it a try and let you know the results. Awesome library by the way.

**Comment by realmtian** [comment]
Closing the issue due to inactivity.
