### ISSUE TITLE
Impossible to recover XML request

### ISSUE THREAD

**Issue by enriquei4** [meng-tian/async-soap-guzzle#22]
It would be great to do accesible the XML REQUEST of a client to see the lastrequest, I see debuging that the XML request is in the client object. But is impossible to recover. Why is not possible to recover it?

some like _lastRequest is not working.

**Comment by realmtian** [comment]
Hi @enriquei4 , why you expect `_lastRequest `? Where `_lastRequest ` comes from?

**Comment by enriquepery** [comment]
http://php.net/manual/en/soapclient.getlastrequest.php

**Comment by enriquepery** [comment]
Similar to native soapclient

**Comment by realmtian** [comment]
Hi @enriquei4 and @enriquepery , `Meng\AsyncSoap\Guzzle` is not equivalent to PHP's native `SoapClient` and the documentation never mentioned it supports `__getLastRequest`.

I don't have plan of supporting `__getLastRequest`.

If you really need `__getLastRequest`, it shouldn't be very difficult to implement it yourself.
