### ISSUE TITLE
Need more info in Readme

### ISSUE THREAD

**Issue by Yorchi** [meng-tian/async-soap-guzzle#23]
Hi @meng-tian , first thank you so much for your work, i really apreciate!

I wrote this issue requesting more use cases, example errors responses,SoapFault...

Hope you can update please.

Thanks again!

**Comment by realmtian** [comment]
Hi @Yorchi, thanks for requesting the documentation. I planned to do it long time ago but also keep forgetting it. I will try my best to do it.

In the meantime, you can access the tests of this library to see how it can be used. Additionally, the tests in https://github.com/meng-tian/php-soap-interpreter have many examples.

**Comment by meng-tian** [comment]
Hi @Yorchi, thanks for requesting the documentation. I planned to do it long time ago but also keep forgetting it. I will try my best to do it.

In the meantime, you can access the tests of this library to see how it can be used. Additionally, the tests in https://github.com/meng-tian/php-soap-interpreter have many examples.
