### ISSUE TITLE
Hold more information than the body

### ISSUE THREAD

**Issue by panvid** [meng-tian/async-soap-guzzle#24]
Right now this SoapClient uses only the Guzzle Response Body to work with. For a full usage it would be useful to have information like Header, Status Code etc.

Is there a plan to implement it?

**Comment by realmtian** [comment]
Hi @dpauli, thanks for raising this issue.

There is no plan to implement the HTTP relevant features you mentioned. The main class of this library `Meng\AsyncSoap\Guzzle\SoapClient` is an implementation of `Meng\AsyncSoap\ SoapClientInterface `. The interface is purely SOAP but not coupling to HTTP. I want to make this library as simple as possible.

If you want to utilise the HTTP headers and status code etc, you could try my another library https://github.com/meng-tian/soap-http-binding. soap-http-binding is all about HTTP binding of SOAP so you can easily get HTTP information you need. In fact, this library depends on the HTTP binding library.

**Comment by realmtian** [comment]
Closing the issue due to inactivity.

**Comment by panvid** [comment]
Thanks for the response, I look for the other lib you said :)
