### ISSUE TITLE
Why arguments required?

### ISSUE THREAD

**Issue by KartaviK** [meng-tian/async-soap-guzzle#27]
Some methods in services, witch used soap, have methods that do not need arguments. So i must put empty array to call method but it is unreadable code. Can you make it optional?

**Comment by realmtian** [comment]
Hi @KartaviK , thanks for the advice.

The arguments of the SoapClient in this library is inspired by here: http://php.net/manual/en/soapclient.soapcall.php

I want to make this argument to be more consistent with PHP's SoapClient.

It indeed looks unnecessary for SOAP services that do not require arguments, but I don't think it being very unreadable given that modern PHP versions have `[]` syntax.

Therefore, I am not going to make arguments optional.

**Comment by KartaviK** [comment]
Ok, I undersand your opinion. Thanks for your your answer)
