### ISSUE TITLE
Response Soap Header

### ISSUE THREAD

**Issue by MRZMUH001** [meng-tian/async-soap-guzzle#30]
Hi @meng-tian,

This is a question, not an issue.

Is there any way to get the SOAP-ENV:Header (sample below) from the response after doing a soap call?
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsa="http://www.w3.org/2005/08/addressing">
<SOAP-ENV:Header>
....
</SOAP-ENV:Header>
<SOAP-ENV:Body>
.....
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Edit: After a bit of investigation, I found the answer I was looking for. Basically, we can pass an argument by reference to the client caller function - the client then sets the output headers to this variable.

See $outputHeaders below.

```
$factory = new Factory();
$client = $factory->create(new Client($client_options), $wsdl);
$response = $client->call($name, array $arguments, array $options = null, $inputHeaders = null, array &$outputHeaders = null)
```

Regards,
Bilal

**Comment by MRZMUH001** [comment]
After a bit of investigation, its actually quite straight forward.

Basically, the soap header options we pass to the soap client upon the call request are passed via reference and are modified by with the output headers.

This means we can simply access the same variable (passed by reference) to get the response soap headers.

```
$foo = call($name, array $arguments, array $options = null, $inputHeaders = null, array &$outputHeaders = null)
```

Ans: $outputHeaders

**Comment by realmtian** [comment]
Hi @MRZMUH001 Thanks for raising the question.

I think you have already found the answer. By passing an array (e.g. `[]`) of output headers (`&$outputHeaders`), the SOAP client will set the headers for you. Once the call completed, you will be able to access the headers of SOAP response from `$outputHeaders`.

The usage of the SOAP client here is identical to PHP's native SOAPClient https://www.php.net/manual/en/soapclient.soapcall.php.

I hope this helps.
