### ISSUE TITLE
What about ws-security?

### ISSUE THREAD

**Issue by IgorNoskov** [meng-tian/async-soap-guzzle#31]
Can I use async-soap-guzzle with ws-security?

**Comment by realmtian** [comment]
I don't know either :) Have you tried it?

**Comment by IgorNoskov** [comment]
Thank you for the answer! I tried, but not successfully :)

**Comment by realmtian** [comment]
Does PHP's SoapClient support ws-security? The dependency of this library is taking advantage of PHP's SoapClient. If ws-security isn't supported by PHP's SoapClient, then it will likely also not work here.

**Comment by IgorNoskov** [comment]
Unfortunately, PHP's SoapClient does not support ws-security. I used https://github.com/BeSimple/BeSimpleSoap to work with ws-security. Thank you!
