### ISSUE TITLE
Make response after callAsync implements ResponseInterface

### ISSUE THREAD

**Issue by matoh** [meng-tian/async-soap-guzzle#6]
Hi,

I am using promise with guzzle implementation and as a promise callback i have been using ResponseInterface. Implementation of your asynchronous SOAP request (method callAsync) does not return request that implements ResponseInterface. 

Is there some possible way to get response that implements ResponseInterface ? It would be great if the response from async soap guzzle will be the same as response after calling sendAsync in guzzle implementation.

Thank you very much

**Comment by realmtian** [comment]
Hi @MatoH , `Meng\AsyncSoap\Guzzle\SoapClient` is a SOAP client rather than a HTTP client, so its method returns parsed SOAP values rather than HTTP responses.

Why is your promise must be resolved to a HTTP response? Would you mind provide a code snippet to clarify your questions please?

Thank you.

**Comment by matoh** [comment]
> Why is your promise must be resolved to a HTTP response?

Because in my case i am using abstract class for sending multiple different async API calls with guzzle promises. One of API implementation uses SOAP protocol so i want to use soap async call with guzzle promise and use response that implements ResponseInterface. Also from promise response i could get headers, statuses codes etc. 

> Would you mind provide a code snippet to clarify your questions please?

For some API providers i am sending GET/POST requests and for one other i used SOAP protocol because there is no support for different call. For all of these API calls i have been using abstract class that resolving promises.

Code snippet: http://pastebin.com/WC0H0kEf

**Comment by realmtian** [comment]
@MatoH , as mentioned in the earlier comment, `Meng\AsyncSoap\Guzzle\SoapClient` is a SOAP client. A SOAP client exchanges SOAP messages, not HTTP messages. 

Therefore, `Meng\AsyncSoap\Guzzle\SoapClient` might not be the right class your abstract class should depend on. However, you might find my HTTP binding library helpful (https://github.com/meng-tian/soap-http-binding).

Here is a code snippet shows how to use `HttpBinding` class to achieve what your abstract class expects:

``` php
use function GuzzleHttp\Promise\all;
use GuzzleHttp\Client;
use Meng\AsyncSoap\Guzzle\Factory;
use Meng\Soap\HttpBinding\HttpBinding;
use Meng\Soap\HttpBinding\RequestBuilder;
use Meng\Soap\Interpreter;
use Psr\Http\Message\ResponseInterface;

// GET/POST requests
$client = new Client();
$promise[] = $client->requestAsync("GET", "http://httpbin.org/get");

// SOAP requests - promise will be fulfilled with a PHP value (interpreted from a SOAP response message)
$factory = new Factory();
$client = $factory->create(new Client(), "http://www.webservicex.net/Statistics.asmx?WSDL");
$promise[] = $client->callAsync("GetStatistics", [["X" => [1,2,3]]]);

// SOAP requests - promise will be fulfilled with a Http response (without interpreting the SOAP message in Http body)
$client = new Client();
$promise[] = $client->requestAsync('GET', 'http://www.webservicex.net/Statistics.asmx?WSDL')
    ->then(
        function (ResponseInterface $response) use ($client) {
            $httpBinding = new HttpBinding(
                new Interpreter('data://text/plain;base64,' . base64_encode($response->getBody()->__toString())),
                new RequestBuilder()
            );

            $request = $httpBinding->request('GetStatistics', [['X' => [1,2,3]]]);
            return $client->sendAsync($request);
        }
    );


all($promise)->then(function ($results) {
    foreach ($results as $result) {
        echo 'Resolved to a ' . gettype($result) . ' ' . get_class($result) . PHP_EOL;
    }
})->wait();
```

The output is:

```
Resolved to a object GuzzleHttp\Psr7\Response
Resolved to a object stdClass
Resolved to a object GuzzleHttp\Psr7\Response
```

As you can see, the third approach fulfils promises with Http responses.

Hope this helps. 😄

**Comment by realmtian** [comment]
@MatoH haven't heard from you for a couple of days. I will assume this issue is resolved. Please raise issues again if you have other queries.

**Comment by matoh** [comment]
@meng-tian thank you very much for helping me. With your code example i have achieved expected response that could be used in abstract class.
Sorry for my late reply but your solution helps :-)
