### ISSUE TITLE
Support for local WSDL file

### ISSUE THREAD

**Issue by aelayeb** [meng-tian/async-soap-guzzle#7]
When I'm using local WSDL file, it fails with an error from CURL.
I tried with path like "/some/path/file.wsdl" and "file:///some/path/file.wsdl" but it didn't work.

The error comes from here : https://github.com/meng-tian/async-soap-guzzle/blob/master/src/Factory.php#L33

The SoapClient class support local files and I thought it would be great if it was supported here too.

Maybe add a condition to check if the URI scheme is "file" and load WSDL data without using curl ?

**Comment by realmtian** [comment]
Thanks @aelayeb for your suggestion 😄 . I am going to support local WSDL file in the next release.

**Comment by realmtian** [comment]
@aelayeb , local WSDL file is now supported in https://github.com/meng-tian/async-soap-guzzle/releases/tag/v0.2.4. Thanks again for your recommendation.
