### ISSUE TITLE
Error installing async-soap-guzzle 

### ISSUE THREAD

**Issue by AdriWild** [meng-tian/async-soap-guzzle#9]
```
C:\www\ICE\localization_manager>composer require meng-tian/async-soap-guzzle
?[30;43mThe "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed?[39;49m
```

**Comment by realmtian** [comment]
Hi @AdriWild , did you experience this issue only for package `meng-tian/async-soap-guzzle`? I suspect this is a composer error instead of a `meng-tian/async-soap-guzzle` error. This issue https://github.com/composer/composer/issues/4212 might help.

**Comment by AdriWild** [comment]
Yes, you´re right, that happened exactly in the moment that I installed your repository. Thank you

**Comment by realmtian** [comment]
@AdriWild Okay, could you please provide the verbose debug output?
i.e., `composer require meng-tian/async-soap-guzzle -vvv`

**Comment by realmtian** [comment]
@AdriWild Haven't heard from you for a few days, does this issue still happening?

**Comment by AdriWild** [comment]
Yes, it works, wasn't 
`meng-tian/async-soap-guzzle `
issue, was solved the next day updating composer.

Thank you so much!
